### PR TITLE
[WIP] fix JDBC fatal error

### PR DESCRIPTION
**Pull request by koxudaxi**
This PR fixes unexpected JDBC fatal error when JDBC gets an error.

The bug depends on alpine and a version of `jpype`.
I will merge this PR when `jpype` will be released
## Related Issues
https://github.com/koxudaxi/local-data-api/issues/50
https://github.com/jpype-project/jpype/pull/763

### CODE REVIEW

**Comment by MarkHerhold** [comment]
I believe this PR (combined with master) messes up boolean types. I checked, and master works just fine.

Basically this PR makes the value `"longValue": 1` where it should be `"booleanValue": true`

**Query:**
```
SELECT 1 > 0 AS value;
+---------+
| value   |
|---------|
| True    |
+---------+
SELECT 1
Time: 0.019s
```

**Reproduce:**

```
export RDS_DATA_API_CLIENT_RESOURCE_ARN=arn:aws:rds:us-east-1:123456789012:cluster:dummy
export RDS_DATA_API_CLIENT_SECRETARN=arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy
aws --endpoint-url 'http://localhost:8080' rds-data execute-statement --database 'test' --resource-arn $RDS_DATA_API_CLIENT_RESOURCE_ARN --secret-arn $RDS_DATA_API_CLIENT_SECRETARN --sql 'SELECT 1 AS hi'
```

**On `koxudaxi/local-data-api:0.4.13`** 

```
      executeStatement({
        secretArn: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy',
        resourceArn: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy',
        database: 'test',
        includeResultMetadata: true,
        parameters: [ [length]: 0 ],
        sql: 'SELECT 1 > 0 AS value'
      })

    console.log
      {
        "columnMetadata": [
          {
            "arrayBaseColumnType": 0,
            "isAutoIncrement": false,
            "isCaseSensitive": false,
            "isCurrency": false,
            "isSigned": false,
            "label": "value",
            "name": "value",
            "nullable": 2,
            "precision": 1,
            "scale": 0,
            "tableName": "",
            "type": -7,
            "typeName": "bool"
          }
        ],
        "numberOfRecordsUpdated": 0,
        "records": [
          [
            {
              "booleanValue": true
            }
          ]
        ]
      }

```

**On #69 with master branch merged in:**

```
      executeStatement({
        secretArn: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy',
        resourceArn: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy',
        database: 'test',
        includeResultMetadata: true,
        parameters: [ [length]: 0 ],
        sql: 'SELECT 1 > 0 AS value'
      })

    console.log
      {
        "columnMetadata": [
          {
            "arrayBaseColumnType": 0,
            "isAutoIncrement": false,
            "isCaseSensitive": false,
            "isCurrency": false,
            "isSigned": false,
            "label": "value",
            "name": "value",
            "nullable": 2,
            "precision": 1,
            "scale": 0,
            "tableName": "",
            "type": -7,
            "typeName": "bool"
          }
        ],
        "numberOfRecordsUpdated": 0,
        "records": [
          [
            {
              "longValue": 1
            }
          ]
        ]
      }
```

**Comment by koxudaxi** [comment]
@MarkHerhold
Thank you for your report.
I research the bug.

`JPype1` change to return type of Java from SQL results in a newer version.

I add handling actual JDBC type for DataAPI.

Also, JPype1 doesn't support the latest `jpype`.
I change base image alpine to Debian. the image size will be large.
I don't afraid of the size because this image don't be used as production.

**Comment by koxudaxi** [comment]
image size:
This PR   ->  562MB
0.4.15      ->  239MB

**Comment by MarkHerhold** [comment]
@koxudaxi I think the size increase is completely fine, especially for a development image such as this 👍

**Comment by MarkHerhold** [comment]
I may have been mistaken with my bug report because MySQL's bool is `0`/`1` and Postgres' bool is `true`/`false` 😟

**Comment by koxudaxi** [comment]
@MarkHerhold 
Could we merge this PR into master branch?
How do you think about it?

**Comment by MarkHerhold** [comment]
I'd merge master into this first, ensure CI works, then merge this
I can test a bit more after master is merged into this branch if you like

**Comment by koxudaxi** [comment]
@MarkHerhold 
The integration test passed in this PR.
I have merged the PR.

Would you test the master ?
If we don't see any problem, then I will publish a new image to the docker hub this weekend.

Thank you very much.

**Comment by MarkHerhold** [comment]
@koxudaxi Everything worked well for me on master 👍

**Comment by koxudaxi** [comment]
@MarkHerhold 

I released a new version as `0.5.0 ` :tada:

**Pull request merged**
